### ISSUE TITLE
When subscribing for the newsletter a new window opens  

### ISSUE THREAD

**Issue by SdeWit** [CoderDojoNederland/Website#103]
After submitting name/email and type of email via https://coderdojo.nl/informatie/nieuwsbrief, a new window/tab is opened. It is not a big issue, but not very user friendly either.

**Comment by ChristianVermeulen** [comment]
@SdeWit I don't remember if you come back to coderdojo.nl after the signup. Do you remember? If so, then I'm all for removing the `target=_blank`. But if you remain in the Mailchimp ecosystem I still prefer the new tab.

**Comment by ChristianVermeulen** [comment]
ping @Tmw

**Comment by Tmw** [comment]
Well using `target=_blank` is bad practice overall so i'd say let's get rid of it anyway :)

**Comment by ChristianVermeulen** [comment]
Alrighty! Can you make a PR for this @SdeWit ?
