### ISSUE TITLE
'Corporate' CoderDojo Nederland movie

### ISSUE THREAD

**Issue by SdeWit** [CoderDojoNederland/Website#106]
I think the movie from CoderDojo Rotterdam is really cool. It might be awesome to make a similar video including shots from multiple Dojo's and disciplines (Scratch, Html, bots, minecraft).

**Comment by ChristianVermeulen** [comment]
Cool idea, we definitely want to do this. We would at the same time like to create a dutch version of the 5 `How to start a dojo`-video's. However, we have other priorities at the foundation at the moment. As soon as we have some time for this we will definitely get into this!
