### ISSUE TITLE
VOG Improvements

### ISSUE THREAD

**Issue by ChristianVermeulen** [CoderDojoNederland/Website#115]
- [x] Change text for final email (100% checked is a utopia)
- [ ] ~~First name letters could be regex validated~~
- [x] Make notes field optional
- [x] Volunteer email should be personal email! (add explanation)
- [x] Birthdate is NOT needed!

**Comment by Tmw** [comment]
- [ ] Add unique constraint to e-mail to avoid duplicates
- [ ] Remove current duplicate requests

**Comment by Tmw** [comment]
- [ ] In the admin overview combine first letters and name for easy copy-pasting ☺️

**Comment by ChristianVermeulen** [comment]
Added open points as seperate issues!
