### ISSUE TITLE
Store lat/long of a Dojo when updating its address

### ISSUE THREAD

**Issue by Tmw** [CoderDojoNederland/website#12]

**Comment by ChristianVermeulen** [comment]
We can do this on PreFlush lifecycle callback in Doctrine
As soon as a Dojo entity will be saved to the DB we can geocode the adress, fill the fields and have doctrine save the who shebang.
http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/events.html#preflush
