### ISSUE TITLE
Accepting mentor requests

### ISSUE THREAD

**Issue by SannekevanderMeer** [CoderDojoNederland/Website#120]
In the profiledashboard of my dojo (at coderdojo.nl) there are now several "mentor verzoeken" which leaves me only with an option to accept them. Which I will not, because two of them are nog even mentors at my dojo (yet) and they will have the same rights as me to change stuff.
I would appreciate a "do not accept" or "remove" button next to the "accept" button.

**Comment by ChristianVermeulen** [comment]
🎉 [Though shall have it!](https://github.com/CoderDojoNederland/Website/commit/86efdb0cd345ff0e03039e26dec89d5f7bfbd9f4)

![screenshot 2018-04-24 21 55 48](https://user-images.githubusercontent.com/1062751/39210875-45b1e208-480a-11e8-9b41-3ce2d70acbc1.png)
