### ISSUE TITLE
Dojos > Remove mapview - replace with table view

### ISSUE THREAD

**Issue by ChristianVermeulen** [CoderDojoNederland/Website#80]
Since we now have an amazingly huge list of dojo's the mapview is becoming less user friendly.
This should be replaced with a table view so we can give a little bit more details about the dojo.
The table can include a search filter.

**Comment by hhfhd** [comment]
Is it a idea that the map stops moving? Because in my opinion it's really annoying that the map moves.

**Comment by ChristianVermeulen** [comment]
Yes I totally agree! We can maybe just show it aseems a smaller version in a box somewhere...

**Comment by sandervdo** [comment]
@ChristianVermeulen +1 that.
I do like the overview of all dojo's, so rather put it in a box (and not full page) than removing it. 😄

**Comment by hhfhd** [comment]
![cd_map](https://cloud.githubusercontent.com/assets/10485665/19803989/fe3d65a0-9d0b-11e6-8262-ebef586f1a51.png)

I was thinking over something like this

**Comment by hhfhd** [comment]
Maybe the box can contain an alphabetical section where the first letter of the city can selected and then show the list of that letter. So the list is much clear. This only for the list of all dojo's

**Comment by ChristianVermeulen** [comment]
@hhfhd Yes you are on the right track. Maybe make a quick mock-up of the 2 pages?

The agenda doesn't need a map I think, it can probably just hold a table (like on the homepage) and a filter to filter by location or something.

The dojo overview can also be a table sorted by city (careful with `Den Haag` vs `'s Gravenhage` kind of things in sorting, we already have that problem with some dojo's :p) and the map below or above it, or next to it. Also make sure to disable the map for mobile, it takes up some precious traffic and memory.

**Comment by ChristianVermeulen** [comment]
The map will be overhault in #165.
